'use client'
import React from 'react'
import CreateCustomerView from './_components/create-customer-view'
import CustomerLoading from './_components/customer-loading'
import CustomerTable from './_components/customer-table'
import RecentActivity from './_components/recent-activity'


type Props = {}

interface Customer {
  id: string
  name: string
  email: string
  phone?: string
  website?: string
  contactPerson?: string
  address?: string
  addressLine2?: string
  invoiceCount: number
  openProjects: number
  pendingContracts: number
  rating: number
  dateCreated: string
  status: "active" | "inactive" | "pending"
  lastActivity: string
  completedRevenue: number
  avatar?: string
  performanceScore?: number
}

const mockCustomers: Customer[] = [
  {
    id: "1",
    name: "Acme Inc",
    email: "contact@acme.com",
    phone: "+1 (555) 123-4567",
    website: "acme.com",
    contactPerson: "John Doe",
    address: "123 Main Street",
    addressLine2: "Suite 100",
    invoiceCount: 12,
    openProjects: 3,
    pendingContracts: 2,
    rating: 4.8,
    status: "active",
    lastActivity: "2 hours ago",
    dateCreated: "2024-01-15",
    completedRevenue: 45000,
    avatar: "/placeholder.svg?height=40&width=40&text=AI",
    performanceScore: 88,
  },
  {
    id: "2",
    name: "TechCorp Solutions",
    email: "hello@techcorp.com",
    phone: "+1 (555) 987-6543",
    website: "techcorp.com",
    contactPerson: "Jane Smith",
    address: "456 Tech Avenue",
    addressLine2: "Floor 5",
    invoiceCount: 8,
    openProjects: 1,
    pendingContracts: 1,
    rating: 4.2,
    status: "active",
    lastActivity: "1 day ago",
    dateCreated: "2024-02-20",
    completedRevenue: 28000,
    avatar: "/placeholder.svg?height=40&width=40&text=TC",
    performanceScore: 76,
  },
  {
    id: "3",
    name: "Digital Dynamics",
    email: "info@digitaldynamics.com",
    phone: "+1 (555) 456-7890",
    website: "digitaldynamics.com",
    contactPerson: "Mike Johnson",
    address: "789 Innovation Drive",
    addressLine2: "Floor 5",
    invoiceCount: 15,
    openProjects: 5,
    pendingContracts: 3,
    rating: 4.9,
    status: "active",
    lastActivity: "3 hours ago",
    dateCreated: "2023-11-10",
    completedRevenue: 67000,
    avatar: "/placeholder.svg?height=40&width=40&text=DD",
    performanceScore: 92,
  },
  {
    id: "4",
    name: "StartupXYZ",
    email: "team@startupxyz.com",
    phone: "+1 (555) 321-0987",
    website: "startupxyz.com",
    contactPerson: "Sarah Wilson",
    address: "321 Startup Lane",
    invoiceCount: 4,
    openProjects: 2,
    pendingContracts: 0,
    rating: 3.8,
    status: "pending",
    lastActivity: "1 week ago",
    dateCreated: "2024-03-05",
    completedRevenue: 12000,
    avatar: "/placeholder.svg?height=40&width=40&text=SX",
    performanceScore: 65,
  },
  {
    id: "5",
    name: "Enterprise Corp",
    email: "contact@enterprise.com",
    phone: "+1 (555) 654-3210",
    website: "enterprise.com",
    contactPerson: "Robert Brown",
    address: "654 Corporate Blvd",
    invoiceCount: 25,
    openProjects: 8,
    pendingContracts: 5,
    rating: 4.6,
    status: "active",
    lastActivity: "5 minutes ago",
    dateCreated: "2023-08-12",
    completedRevenue: 125000,
    avatar: "/placeholder.svg?height=40&width=40&text=EC",
    performanceScore: 90,
  },
  {
    id: "6",
    name: "Global Systems",
    email: "info@globalsystems.com",
    phone: "+1 (555) 789-0123",
    website: "globalsystems.com",
    contactPerson: "Lisa Chen",
    address: "987 Global Plaza",
    invoiceCount: 18,
    openProjects: 4,
    pendingContracts: 2,
    rating: 4.4,
    status: "active",
    lastActivity: "30 minutes ago",
    dateCreated: "2023-12-01",
    completedRevenue: 89000,
    avatar: "/placeholder.svg?height=40&width=40&text=GS",
    performanceScore: 80,
  },
  {
    id: "7",
    name: "InnovateLab",
    email: "hello@innovatelab.com",
    phone: "+1 (555) 234-5678",
    website: "innovatelab.com",
    contactPerson: "David Kim",
    address: "111 Innovation Way",
    invoiceCount: 7,
    openProjects: 3,
    pendingContracts: 1,
    rating: 4.1,
    status: "active",
    lastActivity: "2 days ago",
    dateCreated: "2024-01-28",
    completedRevenue: 34000,
    avatar: "/placeholder.svg?height=40&width=40&text=IL",
    performanceScore: 70,
  },
  {
    id: "8",
    name: "CloudFirst Technologies",
    email: "support@cloudfirst.com",
    phone: "+1 (555) 345-6789",
    website: "cloudfirst.com",
    contactPerson: "Emily Rodriguez",
    address: "222 Cloud Street",
    invoiceCount: 22,
    openProjects: 6,
    pendingContracts: 4,
    rating: 4.7,
    status: "active",
    lastActivity: "1 hour ago",
    dateCreated: "2023-09-15",
    completedRevenue: 98000,
    avatar: "/placeholder.svg?height=40&width=40&text=CF",
    performanceScore: 85,
  },
  {
    id: "9",
    name: "NextGen Solutions",
    email: "contact@nextgen.com",
    phone: "+1 (555) 456-7891",
    website: "nextgen.com",
    contactPerson: "Alex Thompson",
    address: "333 Future Blvd",
    invoiceCount: 11,
    openProjects: 2,
    pendingContracts: 1,
    rating: 4.3,
    status: "inactive",
    lastActivity: "2 weeks ago",
    dateCreated: "2023-10-22",
    completedRevenue: 56000,
    avatar: "/placeholder.svg?height=40&width=40&text=NG",
    performanceScore: 75,
  },
  {
    id: "10",
    name: "DataFlow Inc",
    email: "info@dataflow.com",
    phone: "+1 (555) 567-8912",
    website: "dataflow.com",
    contactPerson: "Maria Garcia",
    address: "444 Data Drive",
    invoiceCount: 16,
    openProjects: 7,
    pendingContracts: 3,
    rating: 4.5,
    status: "active",
    lastActivity: "4 hours ago",
    dateCreated: "2023-07-08",
    completedRevenue: 78000,
    avatar: "/placeholder.svg?height=40&width=40&text=DF",
    performanceScore: 82,
  },
  {
    id: "11",
    name: "SecureNet Systems",
    email: "admin@securenet.com",
    phone: "+1 (555) 678-9123",
    website: "securenet.com",
    contactPerson: "James Wilson",
    address: "555 Security Lane",
    invoiceCount: 9,
    openProjects: 1,
    pendingContracts: 0,
    rating: 4.0,
    status: "pending",
    lastActivity: "3 days ago",
    dateCreated: "2024-02-14",
    completedRevenue: 42000,
    avatar: "/placeholder.svg?height=40&width=40&text=SN",
    performanceScore: 60,
  },
  {
    id: "12",
    name: "WebCraft Studios",
    email: "hello@webcraft.com",
    phone: "+1 (555) 789-1234",
    website: "webcraft.com",
    contactPerson: "Sophie Anderson",
    address: "666 Design District",
    invoiceCount: 13,
    openProjects: 4,
    pendingContracts: 2,
    rating: 4.6,
    status: "active",
    lastActivity: "6 hours ago",
    dateCreated: "2023-06-30",
    completedRevenue: 61000,
    avatar: "/placeholder.svg?height=40&width=40&text=WC",
    performanceScore: 88,
  },
  {
    id: "13",
    name: "AI Ventures",
    email: "contact@aiventures.com",
    phone: "+1 (555) 891-2345",
    website: "aiventures.com",
    contactPerson: "Dr. Ryan Lee",
    address: "777 AI Boulevard",
    invoiceCount: 20,
    openProjects: 9,
    pendingContracts: 6,
    rating: 4.8,
    status: "active",
    lastActivity: "15 minutes ago",
    dateCreated: "2023-05-18",
    completedRevenue: 156000,
    avatar: "/placeholder.svg?height=40&width=40&text=AV",
    performanceScore: 95,
  },
  {
    id: "14",
    name: "MobileFirst Apps",
    email: "team@mobilefirst.com",
    phone: "+1 (555) 912-3456",
    website: "mobilefirst.com",
    contactPerson: "Taylor Swift",
    address: "888 Mobile Plaza",
    invoiceCount: 6,
    openProjects: 2,
    pendingContracts: 1,
    rating: 3.9,
    status: "active",
    lastActivity: "1 day ago",
    dateCreated: "2024-04-02",
    completedRevenue: 29000,
    avatar: "/placeholder.svg?height=40&width=40&text=MF",
    performanceScore: 78,
  },
  {
    id: "15",
    name: "BlockChain Dynamics",
    email: "info@blockchain.com",
    phone: "+1 (555) 123-4567",
    website: "blockchain.com",
    contactPerson: "Chris Johnson",
    address: "999 Crypto Street",
    invoiceCount: 14,
    openProjects: 5,
    pendingContracts: 3,
    rating: 4.2,
    status: "active",
    lastActivity: "8 hours ago",
    dateCreated: "2023-04-25",
    completedRevenue: 87000,
    avatar: "/placeholder.svg?height=40&width=40&text=BD",
    performanceScore: 84,
  },
  {
    id: "16",
    name: "GreenTech Solutions",
    email: "contact@greentech.com",
    phone: "+1 (555) 234-5678",
    website: "greentech.com",
    contactPerson: "Emma Davis",
    address: "101 Eco Avenue",
    invoiceCount: 10,
    openProjects: 3,
    pendingContracts: 2,
    rating: 4.4,
    status: "inactive",
    lastActivity: "1 month ago",
    dateCreated: "2023-03-12",
    completedRevenue: 52000,
    avatar: "/placeholder.svg?height=40&width=40&text=GT",
    performanceScore: 72,
  },
  {
    id: "17",
    name: "FinTech Innovations",
    email: "hello@fintech.com",
    phone: "+1 (555) 345-6789",
    website: "fintech.com",
    contactPerson: "Michael Brown",
    address: "202 Finance Row",
    invoiceCount: 19,
    openProjects: 6,
    pendingContracts: 4,
    rating: 4.7,
    status: "active",
    lastActivity: "2 hours ago",
    dateCreated: "2023-01-20",
    completedRevenue: 134000,
    avatar: "/placeholder.svg?height=40&width=40&text=FI",
    performanceScore: 91,
  },
  {
    id: "18",
    name: "HealthTech Corp",
    email: "support@healthtech.com",
    phone: "+1 (555) 456-7890",
    website: "healthtech.com",
    contactPerson: "Dr. Lisa Wang",
    address: "303 Medical Center",
    invoiceCount: 17,
    openProjects: 8,
    pendingContracts: 5,
    rating: 4.9,
    status: "active",
    lastActivity: "45 minutes ago",
    dateCreated: "2022-12-05",
    completedRevenue: 112000,
    avatar: "/placeholder.svg?height=40&width=40&text=HT",
    performanceScore: 94,
  },
  {
    id: "19",
    name: "EduTech Platform",
    email: "info@edutech.com",
    phone: "+1 (555) 567-8901",
    website: "edutech.com",
    contactPerson: "Professor John Smith",
    address: "404 Learning Lane",
    invoiceCount: 12,
    openProjects: 4,
    pendingContracts: 2,
    rating: 4.1,
    status: "pending",
    lastActivity: "5 days ago",
    dateCreated: "2024-05-10",
    completedRevenue: 68000,
    avatar: "/placeholder.svg?height=40&width=40&text=ET",
    performanceScore: 79,
  },
  {
    id: "20",
    name: "SportsTech Analytics",
    email: "team@sportstech.com",
    phone: "+1 (555) 678-9012",
    website: "sportstech.com",
    contactPerson: "Coach Mike Wilson",
    address: "505 Stadium Drive",
    invoiceCount: 8,
    openProjects: 2,
    pendingContracts: 1,
    rating: 4.0,
    status: "active",
    lastActivity: "12 hours ago",
    dateCreated: "2024-06-01",
    completedRevenue: 38000,
    avatar: "/placeholder.svg?height=40&width=40&text=ST",
    performanceScore: 68,
  },
]


export default function CustomersPage({}: Props) {
  const handleSearch = (value: string) => {
    // TODO: Implement customer search logic
    console.log("Searching for customer:", value)
  }
  return (
    <div className='w-full py-4 px-6 border border-bexoni'>
        <CreateCustomerView onSearch={handleSearch} />
        <RecentActivity />
        <CustomerTable customer={mockCustomers} />
    </div>
  )
}